package Throw;

import java.io.File;
import java.io.IOException;
import java.util.Scanner;

public class ThrowExceptionExample {
	public static void main(String[] args){
		Scanner sc = new Scanner(System.in);
		System.out.println("생성할 파일 이름을 입력하세요: ");
		String fileName = sc.nextLine();
		File f = createFile(fileName+".txt"); 	
		System.out.println("파일생성완료>>");
	}
	public static File createFile(String fileName) {
		try {
			if(fileName == null || fileName.equals("")) {
			throw new Exception("이름이 잘못 되었습니다");
				}
			}catch (Exception e) {
				// TODO: handle exception
				fileName = "제목없음.txt";
			}finally {
				File f = new File(fileName);
				create(f);
				return f;
			}
	}
	
	static void create(File f) {
		try {
			f.createNewFile();
		} catch (IOException e) {
			// TODO 자동 생성된 catch 블록
			System.out.println("파일 생성에 문제가 발생했습니다.");
		}
	}
}
